name: Create Release and Publish NuGet Package

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build_test_publish:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
        source-url: https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json
      env:
        NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Extract matricula for version
      id: extract_matricula
      run: echo "matricula=U2-04" >> $GITHUB_OUTPUT
      
    - name: Restore dependencies
      run: dotnet restore EcommerceApp/EcommerceApp.sln
      
    - name: Build
      run: dotnet build EcommerceApp/EcommerceApp.sln --configuration Release --no-restore -p:Version=1.0.0-${{ steps.extract_matricula.outputs.matricula }}
      
    - name: Test
      run: dotnet test EcommerceApp/EcommerceApp.sln --configuration Release --no-build
      
    - name: Pack
      run: dotnet pack EcommerceApp/EcommerceApp.Api/EcommerceApp.Api.csproj --configuration Release --no-build -p:PackageVersion=1.0.0-${{ steps.extract_matricula.outputs.matricula }} -o nuget-packages
      
    - name: Publish NuGet Package to GitHub Packages
      run: dotnet nuget push nuget-packages/*.nupkg --api-key ${{ secrets.GITHUB_TOKEN }} --source https://nuget.pkg.github.com/${{ github.repository_owner }}
      
    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        files: nuget-packages/*.nupkg
        name: Release ${{ steps.extract_matricula.outputs.matricula }}
        draft: false
        prerelease: false
